### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by motogon** [fratton/homebridge-tuya-web#1]
Hi . 

Jun 25 18:20:29 dend homebridge[9706]: [2020-6-25 9:20:29 PM] [TuyaWebPlatform] Error retrieving devices states Error: No valid response from API
Jun 25 18:20:29 dend homebridge[9706]:     at sendRequestJson (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/lib/tuyawebapi.js:78:18)
Jun 25 18:20:29 dend homebridge[9706]:     at sendRequest (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/lib/tuyawebapi.js:309:11)
Jun 25 18:20:29 dend homebridge[9706]:     at Request.request [as _callback] (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
Jun 25 18:20:29 dend homebridge[9706]:     at Request.self.callback (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/node_modules/request/request.js:185:22)
Jun 25 18:20:29 dend homebridge[9706]:     at Request.emit (events.js:198:13)
Jun 25 18:20:29 dend homebridge[9706]:     at Request.<anonymous> (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/node_modules/request/request.js:1154:10)
Jun 25 18:20:29 dend homebridge[9706]:     at Request.emit (events.js:198:13)
Jun 25 18:20:29 dend homebridge[9706]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/@thepotterfamily/homebridge-tuya-web/node_modules/request/request.js:1076:12)
Jun 25 18:20:29 dend homebridge[9706]:     at Object.onceWrapper (events.js:286:20)
Jun 25 18:20:29 dend homebridge[9706]:     at IncomingMessage.emit (events.js:203:15)
Jun 25 18:20:29 dend homebridge[9706]:     at endReadableNT (_stream_readable.js:1145:12)
Jun 25 18:20:29 dend homebridge[9706]:     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by motogon** [comment]
my config : 

{
            "options": {
                "username": "xxxxxx",
                "password": "xxxxx",
                "countryCode": "+7",
                "platform": "tuya",
                "pollingInterval": 5
            },
            "name": "TuyaWebPlatform",
            "platform": "TuyaWebPlatform"
        },
