### ISSUE TITLE
Errors in latest version of Homebridge

### ISSUE THREAD

**Issue by mbriney** [fratton/homebridge-tuya-web#4]
I'm seeing the following errors after installing Homebridge 1.1.2.

[8/14/2020, 10:12:55 AM] [TuyaWebPlatform] [GET][Dining Table] Characteristic.Hue Error: Error: Invalid payload in response:
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:119:20
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:309:11
    at Request._callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[8/14/2020, 10:12:55 AM] [TuyaWebPlatform] [GET][Dining Table] Characteristic.Saturation Error: Error: Invalid payload in response:
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:119:20
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:309:11
    at Request._callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[8/14/2020, 10:12:56 AM] [TuyaWebPlatform] [GET][Dining Table] Characteristic.Brightness Error: Error: Invalid payload in response:
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:119:20
    at /usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:309:11
    at Request._callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@fratton/homebridge-tuya-web/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by mgmellia** [comment]
Same problem here. Since I upgraded to the latest version of HB, the plugin is not working properly anymore sigh.

**Comment by roadwan** [comment]
Same problem here. Still receiving notification Device is offline, check connection. Via Application Tuya it works but via plugin to HomeBridge no success. Thank you for looking on pblm

**Comment by mbierman** [comment]
No problem here. If there is any information I can provide to help, let me know.
